#!/bin/bash

echo "Check if uv is installed"
if ! command -v uv > /dev/null 2>&1; then
    echo "uv is not installed. Installing uv now..."
    # Install uv
    curl -LsSf https://astral.sh/uv/install.sh | sh
    # After installing uv, reload environment variables to use uv immediately
    source "$HOME/.local/bin/env"
    echo "uv installed successfully."
fi

echo "Installation completed!"
echo "You can now run the settings.bat script manually if needed."

exit 0
